# Generated by Django 5.1.5 on 2025-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_servicecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('order', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
