# Generated by Django 5.1.5 on 2025-07-24 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_service_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, choices=[('fa-keyboard', 'تایپ'), ('fa-tools', 'تعمیرات'), ('fa-user-plus', 'ثبت\u200cنام'), ('fa-file-alt', 'ترجمه'), ('fa-code', 'برنامه\u200cنویسی'), ('fa-paint-brush', 'طراحی گرافیک')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
