# Generated by Django 5.1.5 on 2025-07-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_service_price_order_file_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, choices=[('fa-keyboard', 'تایپ'), ('fa-tools', 'تعمیرات'), ('fa-user-plus', 'ثبت\u200cنام'), ('fa-file-alt', 'ترجمه'), ('fa-code', 'برنامه\u200cنویسی'), ('fa-paint-brush', 'طراحی گرافیک'), ('fa-laptop', 'لپ\u200cتاپ'), ('fa-server', 'سرور'), ('fa-database', 'دیتابیس'), ('fa-print', 'پرینت'), ('fa-camera', 'عکاسی'), ('fa-video', 'فیلم\u200cبرداری'), ('fa-mobile-alt', 'موبایل'), ('fa-cogs', 'تنظیمات'), ('fa-network-wired', 'شبکه'), ('fa-cloud', 'کلود'), ('fa-bug', 'دیباگ'), ('fa-shield-alt', 'امنیت'), ('fa-file-excel', 'اکسل'), ('fa-file-word', 'وورد'), ('fa-file-powerpoint', 'پاورپوینت'), ('fa-photo-video', 'چندرسانه\u200cای'), ('fa-globe', 'وب\u200cسایت'), ('fa-shopping-cart', 'فروشگاه آنلاین')], max_length=50, null=True),
        ),
    ]
