# Generated by Django 5.1.5 on 2025-07-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_order_is_done_order_status_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='توضیحات ادمین'),
        ),
    ]
