# Generated by Django 5.1.5 on 2025-07-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=20)),
                ('icon_class', models.CharField(help_text='مثلاً: fas fa-users', max_length=50)),
            ],
        ),
    ]
